# Generated by Django 5.2.2 on 2025-06-10 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, default='Нет описания', max_length=1024, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название коллекции')),
                ('description', models.TextField(blank=True, default='Нет описания', max_length=1024, null=True, verbose_name='Описание коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название одежды')),
                ('description', models.TextField(blank=True, default='Нет описания', max_length=1024, null=True, verbose_name='Описание одежды')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('size', models.PositiveBigIntegerField(default=32, verbose_name='Размер')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Изображение')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Доступность к покупке')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UP.category', verbose_name='Категория')),
                ('collection', models.ManyToManyField(to='UP.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
            },
        ),
    ]
