# Generated by Django 5.2.2 on 2025-06-16 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up1', '0003_faq_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_firstname', models.CharField(max_length=255, verbose_name='Фамилия покупателя')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('buyer_surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество покупателя')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к заказу')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('SH', 'Вывоз из магазина'), ('CR', 'Курьер'), ('PP', 'Пункт выдачи заказов')], default='SH', max_length=2, verbose_name='Способ доставки')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка на товар (%)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='up1.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='up1.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='up1.PosOrder', to='up1.product', verbose_name='Товары'),
        ),
    ]
